### ISSUE TITLE
host is required

### ISSUE THREAD

**Issue by amitgandhinz** [steedferns/homebridge-roomba980#7]
Hi

Im trying to get the roomba980 home bridge plugin installed.  I followed the guide for the other roomba package for installation.

However, when homebridge runs, and tries to use the plugin, i get the following error:

```
/usr/local/lib/node_modules/homebridge-roomba980/node_modules/dorita980/lib/v2/local.js:8
  if (!host) throw new Error('host is required.');
             ^

Error: host is required.
    at localV2 (/usr/local/lib/node_modules/homebridge-roomba980/node_modules/dorita980/lib/v2/local.js:8:20)
    at new local (/usr/local/lib/node_modules/homebridge-roomba980/node_modules/dorita980/index.js:17:10)
    at RoombaAccessory.getPowerState (/usr/local/lib/node_modules/homebridge-roomba980/index.js:25:31)
    at emitThree (events.js:116:13)
    at Characteristic.On.emit (events.js:194:7)
    at Characteristic.On.Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:120:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:634:20)
    at Array.forEach (native)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:598:8)
    at emitMany (events.js:127:13)
    at HAPServer.emit (events.js:201:7)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:926:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

I have the IP and the blid/pw set up.  Any ideas what I'm missing?

Thanks.

**Comment by amitgandhinz** [comment]
Okay, I figured out the issue.  The readme for the https://github.com/umesan/homebridge-roomba plugin refers to an `ipaddress` in the configuration.  However, this plugin uses the property `robotIP` instead.  

I suggest updating the Readme with the correct properties required to avoid this confusion.
